// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv1KFczewoOQk-h5b5Qu9WqlQLlW-NUX8',
    appId: '1:337553111898:web:237a4119de0ac2f67fd163',
    messagingSenderId: '337553111898',
    projectId: 'skillpay-36c4a',
    authDomain: 'skillpay-36c4a.firebaseapp.com',
    storageBucket: 'skillpay-36c4a.firebasestorage.app',
    measurementId: 'G-1028E6DCQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDP3b6iv0L9R0LZxFi2crZlMiUrRp-WYM',
    appId: '1:337553111898:android:2f5ec04e9a54d2877fd163',
    messagingSenderId: '337553111898',
    projectId: 'skillpay-36c4a',
    storageBucket: 'skillpay-36c4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnMo7Fv-RWnIIUjHKk1UwAdAQiQSaOuLo',
    appId: '1:337553111898:ios:fd31581437a1a7007fd163',
    messagingSenderId: '337553111898',
    projectId: 'skillpay-36c4a',
    storageBucket: 'skillpay-36c4a.firebasestorage.app',
    iosBundleId: 'com.example.skillpayWorkers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnMo7Fv-RWnIIUjHKk1UwAdAQiQSaOuLo',
    appId: '1:337553111898:ios:fd31581437a1a7007fd163',
    messagingSenderId: '337553111898',
    projectId: 'skillpay-36c4a',
    storageBucket: 'skillpay-36c4a.firebasestorage.app',
    iosBundleId: 'com.example.skillpayWorkers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv1KFczewoOQk-h5b5Qu9WqlQLlW-NUX8',
    appId: '1:337553111898:web:9a6bf0ab51684b437fd163',
    messagingSenderId: '337553111898',
    projectId: 'skillpay-36c4a',
    authDomain: 'skillpay-36c4a.firebaseapp.com',
    storageBucket: 'skillpay-36c4a.firebasestorage.app',
    measurementId: 'G-ZX7MLD7DW8',
  );
}
